#!/bin/bash

LOG=/var/log/audless-play.log
TRACKLOG=/var/log/audless-track.log
MAXLOG=$((1024 * 1024))

function log {
    echo $(date "+%Y-%m-%d %T") :: $*
}

# truncate logfiles if too big
if [ -f $LOG ]; then
    sz=$(stat -f%z $LOG)
    if [ $sz -gt $MAXLOG ]; then
        echo -n > $LOG
        log "rolled $LOG"
    fi
fi
if [ -f $TRACKLOG ]; then
    sz=$(stat -f%z $TRACKLOG)
    if [ $sz -gt $MAXLOG ]; then
        echo -n > $TRACKLOG
        log "rolled $TRACKLOG"
    fi
fi

dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
pidfile=${HOME}/play_next.pid

if [ -f ${pidfile} ]; then
    log "already playing, found ${pidfile}"
    exit 1
fi

activation=$(sqlite3 ${dir}/audless.db "SELECT value FROM config WHERE key='activation_bytes'")
next_up=$(sqlite3 ${dir}/audless.db "SELECT file,pos FROM queue WHERE pos <= end ORDER BY rank DESC LIMIT 1")

if [ "${next_up}" = "" ]; then
    log "queue is empty"
    exit 0
fi

file=$(echo $next_up | awk -F'|' '{print $1}')
seek=$(echo $next_up | awk -F'|' '{print $2}')

log "starting ${file} at ${seek}"

SDL_AUDIODRIVER=alsa AUDIODEV=hw ffplay -activation_bytes ${activation} \
    -hide_banner \
    -stats \
    -nodisp \
    -autoexit \
    -ss ${seek} \
    "${file}" >>$LOG 2>&1 &

pid=$!
disown ${pid}

log "creating ${pidfile}"
echo ${pid} > ${pidfile}

log "launching tracker"
nohup ${dir}/track "${file}" >>$TRACKLOG 2>&1 &
disown $!
