#!/bin/bash

QUEUE=/var/books
DIR=$(dirname $(readlink -f $0))
LOG=/var/log/audless/queue.log
MAXLOG=$((1024 * 128))

function log {
    echo $(date "+%Y-%m-%d %T") :: $*
}

exec >> $LOG 2>&1

# truncate logfile if it's too big
if [ -f $LOG ]; then
    sz=$(stat -c%s $LOG)
    if [ $sz -gt $MAXLOG ]; then
        echo -n > $LOG
        log "rolled $LOG"
    fi
fi

for f in ${QUEUE}/*.aax; do
    log "queueing: ${f}"
    sqlite3 ${DIR}/audless.db "INSERT OR IGNORE INTO queue(file,rank) VALUES ('${f}', (SELECT MAX(rank)+1 FROM queue))"

    count=$(sqlite3 audless.db "SELECT COUNT(*) FROM queue WHERE file='${f}' AND end=0")
    if [ ${count} -eq 1 ]; then
        end=$(ffmpeg -i ${f} -f ffmetadata - 2>&1 | grep "Chapter #" | tail -1 | awk '{print $6}')
        log "${f} ends at ${end}"
        sqlite3 ${DIR}/audless.db "UPDATE queue SET end=${end} WHERE file='${f}'"
    fi
done
